name: myhealthbd_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.32+49

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  rxdart: ^0.27.0
  webview_flutter: ^2.0.8
  flutter_webview_plugin: ^0.4.0
  dropdown_search: ^0.6.1
  hexcolor: ^2.0.3
  package_info: ^2.0.2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  modal_bottom_sheet: ^2.0.0
  unicorndial: ^1.1.5
  sliding_up_panel: ^2.0.0+1
  flutter_speed_dial: ^3.0.5
  flutter_staggered_grid_view: ^0.4.0
  ripple_effect: ^0.1.1
  dashed_container: ^1.0.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  bot_toast: ^4.0.1
  logger: ^1.0.0
  equatable: ^2.0.2
  get_it: ^7.1.3
  jwt_decode: ^0.3.1
  dartz: ^0.9.2
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  after_layout: ^1.1.0
  youtube_player_flutter: ^8.0.0
  cached_network_image: ^3.0.0
  page_transition: ^2.0.2
  path: ^1.8.0
  open_file: ^3.2.1
  flutter_pdfview: ^1.1.0
  fluttertoast: ^8.0.7
  carousel_slider: ^3.0.0
  flutter_html: ^2.0.0
  percent_indicator: ^3.0.1
  image_picker: ^0.7.5+3
  shimmer: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  file_picker: ^3.0.2+2
  get: ^4.1.4
  url_launcher: ^6.0.4
  data_connection_checker: ^0.3.4
  flutter_svprogresshud:
  photo_view: ^0.9.2



dev_dependencies:
  multi_select_item: ^1.0.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  path: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
